# Generated by Django 5.1.1 on 2024-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Summer Semester')], max_length=1)),
                ('academic_year', models.CharField(max_length=9)),
                ('max_students', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
