# Generated by Django 5.1.1 on 2024-09-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='status',
            new_name='open_for_registration',
        ),
    ]
